# Generated by Django 4.1.13 on 2023-11-16 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('MobileNumber', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=100)),
                ('CustomerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('PurchaseID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('ProductName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FliprAPI.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Pincode', models.CharField(max_length=10)),
                ('City', models.CharField(max_length=100)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FliprAPI.customer')),
                ('PurchaseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FliprAPI.order')),
            ],
        ),
    ]
